name: CD 

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  AWS_REGION: us-west-2

jobs:
  deploy-app1:
    name: Deploy app 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
        
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Fetch Shared ECS Cluster ID
        id: fetch-cluster-id
        run: |
          echo "Fetching ECS Cluster ID for environment: ${{ inputs.environment }}"
          echo "Debug: Listing all ECS clusters in region ${{ env.AWS_REGION }}"
          aws ecs list-clusters --output json
          ECS_CLUSTER_ID=$(aws ecs list-clusters --query "clusterArns[?contains(@, '${{ inputs.environment }}')]" --output text)
          if [ -z "$ECS_CLUSTER_ID" ]; then
            echo "Error: ECS Cluster ID not found for environment: ${{ inputs.environment }}"
            echo "Ensure the cluster exists, the name matches, and the region is correct."
            exit 1
          fi
          echo "ECS_CLUSTER_ID=$ECS_CLUSTER_ID" >> $GITHUB_ENV
          echo "ECS Cluster ID: $ECS_CLUSTER_ID"
          
      - name: Deploy app 1 to ECS
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER_ID \
            --service ${{ inputs.environment }}-app1-service --force-new-deployment

  # Second app deployment
  deploy-app2:
    name: Deploy app 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
        
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Fetch Shared ECS Cluster ID
        id: fetch-cluster-id
        run: |
          echo "Fetching ECS Cluster ID for environment: ${{ inputs.environment }}"
          echo "Debug: Listing all ECS clusters in region ${{ env.AWS_REGION }}"
          aws ecs list-clusters --output json
          ECS_CLUSTER_ID=$(aws ecs list-clusters --query "clusterArns[?contains(@, '${{ inputs.environment }}')]" --output text)
          if [ -z "$ECS_CLUSTER_ID" ]; then
            echo "Error: ECS Cluster ID not found for environment: ${{ inputs.environment }}"
            echo "Ensure the cluster exists, the name matches, and the region is correct."
            exit 1
          fi
          echo "ECS_CLUSTER_ID=$ECS_CLUSTER_ID" >> $GITHUB_ENV
          echo "ECS Cluster ID: $ECS_CLUSTER_ID"
          
      - name: Deploy app 2 to ECS
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER_ID \
            --service ${{ inputs.environment }}-app2-service --force-new-deployment
